### PR TITLE
Export APP_STORE_CONNECT_API_KEY_PATH

### PR DESCRIPTION
**Pull request by knox**
### Checklist

- [x] I've read and accepted the [Contribution Guidelines](https://github.com/bitrise-steplib/.github/blob/main/CONTRIBUTING.md)
- Requires PATCH [version update](https://semver.org/)

### Context

Fastlane's environment variables for API Key Auth got unified.

Exporting to the new environment variable is also required to use API Key Auth with fastlane [pilot](https://docs.fastlane.tools/actions/pilot/)

### Changes

Export the path to the generated _api_key.json_ in the environment variable `APP_STORE_CONNECT_API_KEY_PATH`.

For compatiblilty with older fastlane versions (and pass this step's tests) the new variable is exported _in addition_ to existing variable `DELIVER_API_KEY_PATH`. Furthermore other old authentication related environment variables `PILOT_USERNAME` and `PILOT_API_KEY_PATH` get exported now. These should be removed in a later update.

### Investigation details

With this change API Key Auth will work both in [deliver](https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/options.rb#L16) and in [pilot](https://github.com/fastlane/fastlane/blob/master/pilot/lib/pilot/options.rb#L14), too.

The [consolidation was beeing discussed](https://github.com/fastlane/fastlane/discussions/18145) in the fastlane comunity and got [released with 2.175.0](https://github.com/fastlane/fastlane/pull/18181) since.

### CODE REVIEW

**Comment by knox** [comment]
@godrei to the rescue, please

**Comment by godrei** [comment]
Hi @knox ,
this is the error message:

```
[15:32:26]: No value found for 'username'
+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | increment_build_number | 1           |
| 3    | build_app              | 50          |
| 💥   | upload_to_app_store    | 0           |
+------+------------------------+-------------+
[15:32:26]: fastlane finished with errors
[!] No value found for 'username'
#######################################################################
# fastlane 2.175.0 is available. You are on 2.173.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################
Fastlane command: (bundle "_1.17.3_" "exec" "fastlane" "release") failed
If you want to send an issue report to fastlane (https://github.com/fastlane/fastlane/issues/new), you can find the output of fastlane env in the following log file:
/Users/vagrant/deploy/fastlane_env.log
$ bundle "_1.17.3_" "exec" "fastlane" "env"
Command failed, error: exit status 1
```

Is it possible that `deliver` only uses `DELIVER_API_KEY_PATH` env? So instead of replacing the env key, might we should add a new one for `APP_STORE_CONNECT_API_KEY_PATH `?

**Comment by knox** [comment]
> this is the error message

Thank you very much for looking at it, @godrei 

> Is it possible that deliver only uses `DELIVER_API_KEY_PATH` env?

I don't think so. See [here](https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/options.rb#L16).

> So instead of replacing the env key, might we should add a new one

This seems redundant to me. We should rather figure out why `upload_to_app_store` fails. It might be something in the way how the tests invoke it.

At least for my workflows this change works as expected. But i don't acutally `upload_to_appstore` with it.

**Comment by knox** [comment]
> fastlane 2.175.0 is available. You are on 2.173.0

Updating [this](https://github.com/bitrise-io/sample-apps-fastlane-test/blob/master/Gemfile.lock#L51) might fix the test.

**Comment by danielsinclairtill** [comment]
Fellow bitrise user here,
Thanks for pointing this update out here 🙏 

I also saw this issue last week when trying to use some other fastlane actions through this bitrise step which required the App Store Connect API key.
If I am not mistaken, as @knox pointed out, I found out here in fastlane that they [unified ENV vars for App Store Connect API Key](https://github.com/fastlane/fastlane/pull/18181) to the value `APP_STORE_CONNECT_API_KEY_PATH` in release version [2.175.0](https://github.com/fastlane/fastlane/releases/tag/2.175.0).

So my thoughts were updating this to set the env var `APP_STORE_CONNECT_API_KEY_PATH` instead, and update the version of fastlane to `2.175.0` would be a safe option. In this way the bitrise fastlane step can have access to the api key in all fastlane actions, instead of just deliver.
Thank you again!

**Comment by knox** [comment]
@danielsinclairtill thanks for linking https://github.com/fastlane/fastlane/pull/18181

**Comment by godrei** [comment]
Hi @danielsinclairtill and @knox ,
thanks for the contribution!

I think it is better to keep exporting `DELIVER_API_KEY_PATH` too, for now, this way we can support Fastlane version below 2.175.0.

**Review by godrei — APPROVED** [review]

**Pull request merged**
